# Generated by Django 3.2.18 on 2023-05-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.FileField(default=9, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
